# Photo Editor

In [5]:
from tkinter import *

root=Tk()
root.geometry("500x350")
def dropdown():
    print("Hello!!I am building a multimessaging software")

def home():
    print("I am Home button")
menu=Menu(root)
root.config(menu=menu)

submenu=Menu(menu)
menu.add_cascade(label="File",menu=submenu)
submenu.add_command(label="New file",command=dropdown)
submenu.add_command(label="Open",command=dropdown)
submenu.add_separator()
submenu.add_command(label="Exit",command=root.quit)

submenu2=Menu(menu)
menu.add_cascade(label="Help",menu=submenu2)
submenu2.add_command(label="Help",command=dropdown)

#**********ToolBar**********

toolbar=Frame(root,bg="cyan2")
insert_botton=Button(toolbar,text="Home",command=home)
insert_botton.pack(side=LEFT,padx=4,pady=4)

about=Button(toolbar,text="About Us",command=home)
about.pack(side=LEFT,padx=4,pady=4)

toolbar.pack(side=TOP,fill=X)

#*******Status Bar********
status=Label(root,text="Hang on!!!!!!!!!!!!!",bd=1,relief=SUNKEN,anchor=W)#bd-border
status.pack(side=BOTTOM,fill=X)

#*****Message Box******



thelabel=Label(root,text="Welcome to the Multimesssaging Portal",bg="light sea green",fg="gray28")
thelabel.pack(fill=X,pady=6)

topframe=Frame(root)
topframe.pack()
bottomframe=Frame(root)
bottomframe.pack(side=BOTTOM)
photo1=PhotoImage(file="whatsapp.png")
photo2=PhotoImage(file="fb1.png")
photo3=PhotoImage(file="insta2.png")
button1=Button(topframe,text="Whatsapp",image=photo1,compound=TOP)#fg-forground
button2=Button(topframe,text="Facebook",fg="green",image=photo2,compound=TOP) #bg-background
button3=Button(topframe,text="Instagram",fg="gray35",image=photo3,compound=TOP)


button1.pack(side=LEFT,padx=30,pady=60)
button2.pack(side=LEFT,padx=30,pady=60)
button3.pack(side=LEFT,padx=30,pady=60)

whatsapp=PhotoImage(file="whatsapp.png")

label1=Label(root,image=whatsapp)
label1.pack(side=BOTTOM)
root.mainloop()



# Functions for Image Editor

In [1]:
def open_img(): 
    # Select the Imagename from a folder 
    global x
    x = openfilename() 
    # opens the image 
    img = Image.open(x)
    global flag
    flag=1
    #global temp_img
    #temp_img=copy.copy(img)
    # resize the image and apply a high-quality down sampling filter 
    img = img.resize((540,320), Image.ANTIALIAS) 
    # PhotoImage class is used to add image to widgets, icons etc 
    img = ImageTk.PhotoImage(img) 
    # create a label 
    panel = Label(root, image = img) 
    # set the image as img 
    panel.image = img 
    panel.grid(row = 4,column=4,columnspan=20) 
def open_img_direct(x): 
    # Select the Imagename from a folder 
    img = Image.open(x)
    # resize the image and apply a high-quality down sampling filter 
    img = img.resize((540,320), Image.ANTIALIAS) 
    # PhotoImage class is used to add image to widgets, icons etc 
    img = ImageTk.PhotoImage(img) 
    # create a label 
    panel = Label(root, image = img) 
    # set the image as img 
    panel.image = img 
    panel.grid(row = 4,column=4,columnspan=20) 
def openfilename(): 
    # open file dialog box to select image 
    # The dialogue box has a title "Open" 
    filename = filedialog.askopenfilename(title ='"pen') 
    
    return filename
def save(): 
    files = [('All Files', '*.*'),  
             ('JPG', '*.jpg'), 
             ('PNG', '*.png')] 
    file1 = filedialog.asksaveasfile(filetypes = files, defaultextension = files) 
    return file1
def message(info):
    messagebox.showinfo("Information",info)
    
def resize():
    if flag==0:
        messagebox.showwarning('Warning',"No Image Selected")
    else:
        file=x
        img=cv2.imread(file)

        #temp_img=copy.copy(img)

        root1=Tk()
        root1.geometry("300x150")
        root1.title('Resize')
        Label(root1,text="Enter The Dimensions").grid(column=1,row=0,columnspan=5)
        Label(root1,text="Width").grid(column=1,row=1,padx=3,pady=3)
        Label(root1,text="Height").grid(column=2,row=1,padx=3,pady=3)
        w1=Entry(root1)
        h1=Entry(root1)
        w=0
        h=0
        w1.grid(column=1,row=2,padx=3,pady=3)
        h1.grid(column=2,row=2,padx=3,pady=3)
        def submit():
            w=int(w1.get())
            h=int(h1.get())
            img1=cv2.resize(img,(w,h))
            flag=cv2.imwrite(file,img1)
            if flag==True:
                info="Resized Image saved successfully to: "+file
                message(info)
            root1.destroy()
        Button(root1,text="Resize",command=submit).grid(row=4,column=1)
        root1.mainloop()
def addtext():
    pass
def addline():
    if flag==0:
        messagebox.showwarning('Warning',"No Image Selected")
    else:
        file=x
        font=cv2.FONT_HERSHEY_SIMPLEX
        #img=cv2.putText(img,'Enter \"s\" to Save',(20,500),font,1,(255,255,255),5,cv2.LINE_AA)
        def click_event(event,x,y,flags,params):
            if event==cv2.EVENT_LBUTTONDOWN:
                points.append((x,y))
                if len(points)>=2:
                    cv2.line(img,points[-1],points[-2],(15,255,255),3)
                cv2.imshow("image",img)

        img=cv2.imread(file,1)
        global temp_img
        temp_img=copy.copy(img)
        
        cv2.imshow("image",img)
        points=[]
        cv2.setMouseCallback("image",click_event)

        k=cv2.waitKey(0)
        if k==27:
            cv2.destroyAllWindows()
        elif k==ord('s'):
            cv2.imwrite("C:\\Users\\sagar\\Desktop\\My Image Editor Saves\\saves.jpg",img)
            cv2.destroyAllWindows()
            open_img_direct("C:\\Users\\sagar\\Desktop\\My Image Editor Saves\\saves.jpg")
        #cv2.destroyAllWindows()
def nothing1(p):
    pass
def select_your_colour():
    b=0
    g=0
    r=0
    def get_color():
        info="Selcted Color-> Blue: "+str(b)+" Green: "+str(g)+" Red: "+str(r)
        message(info)
    img=np.zeros((240,360,3),np.uint8)
    cv2.namedWindow("image")
    cv2.createTrackbar('B',"image",0,255,nothing1)
    cv2.createTrackbar('G',"image",0,255,nothing1)
    cv2.createTrackbar('R',"image",0,255,nothing1)
    font=cv2.FONT_HERSHEY_SIMPLEX
    text="Enter esc to close"
    
    while(1):
        cv2.putText(img,text,(20,20),font,0.5,((b+120)%255,(g+80)%255,(r+150)%255),1)
        cv2.imshow("image",img)
        k=cv2.waitKey(1) & 0xFF
        if k==27:
            get_color()
            break
        b=cv2.getTrackbarPos('B','image')
        g=cv2.getTrackbarPos('G','image')
        r=cv2.getTrackbarPos('R','image')
        
        img[:]=[b,g,r]
    cv2.destroyAllWindows()
    
def merge_images():
    #1st image
    file1=openfilename()
    file2=openfilename()
    img1=cv2.imread(file1,1)
    img2=cv2.imread(file2,1)
    
    dim=img1.shape
    img1=cv2.resize(img1,(dim[1],dim[0]))
    img2=cv2.resize(img2,(dim[1],dim[0]))
    
    added_images=cv2.add(img1,img2)
    def nothing(x):
    #print(x)
        pass
    img=added_images
    cv2.namedWindow("image")
    cv2.createTrackbar('Alpha','image',0,100,nothing)
    while(1):
        cv2.imshow("image",img)
        k=cv2.waitKey(1) & 0xFF
        if k==27:
            break
        alpha=(cv2.getTrackbarPos("Alpha",'image'))/100
        beta=1-alpha
        
        dst=cv2.addWeighted(img1,alpha,img2,beta,0)
        img[:]=dst
    
    st=cv2.imwrite("C:\\Users\\sagar\\Desktop\\My Image Editor Saves\\saves.jpg",img)
    if st==True:
        info="Blended Image saved successfully to: "+"C:\\Users\\sagar\\Desktop\\My Image Editor Saves\\saves.jpg"
        message(info)
                
    cv2.destroyAllWindows()
def smoothing():
    def nothing(x):
        pass
    if flag==0:
        messagebox.showwarning('Warning',"No Image Selected")
    else:
        file=x
        img=cv2.imread(file)
        cv2.namedWindow("image")
        kn=1
        cv2.createTrackbar("Kernal:",'image',1,10,nothing)
        imgTemp=img
        while(1):
            cv2.imshow("image",img)
            k=cv2.waitKey(1) & 0xFF
            if k==27:
                break
            kn=int(cv2.getTrackbarPos("Kernal:",'image'))
            #kernal=np.ones((kn,kn),np.float32)/(kn*kn)
            dst=cv2.blur(img,(kn,kn))
            img[:]=dst
        
        st=cv2.imwrite('C:\\Users\\sagar\\Desktop\\My Image Editor Saves\\saves.jpg',img)
        if st==True:
            info="Smoothed Image saved successfully to: "+"C:\\Users\\sagar\\Desktop\\My Image Editor Saves\\saves.jpg"
            message(info)
    cv2.destroyAllWindows()
def capture_image():
    pass
def BrightNess():
    if flag==0:
        messagebox.showwarning('Warning',"No Image Selected")
    else:
        file=x
        img1=cv2.imread(file,1)
        
        def nothing(x):
        #print(x)
            pass
        cv2.namedWindow("image")
        cv2.createTrackbar('Alpha','image',0,100,nothing)
        cv2.createTrackbar('Beta','image',0,100,nothing)
        while(1):
            cv2.imshow("image",img1)
            k=cv2.waitKey(1) & 0xFF
            if k==27:
                break
            alpha=(cv2.getTrackbarPos("Alpha",'image'))/100
            beta=(cv2.getTrackbarPos("Beta",'image'))/100
            
            br=np.ones(img1.shape)*beta
            img1=img1+br
            img1[:]=img1
        '''
        st=cv2.imwrite("C:\\Users\\sagar\\Desktop\\My Image Editor Saves\\saves.jpg",img1)
        if st==True:
            info="Blended Image saved successfully to: "+"C:\\Users\\sagar\\Desktop\\My Image Editor Saves\\saves.jpg"
            message(info)
        '''
        cv2.destroyAllWindows()
def addshape():
    pass
def blur():
    pass
def undo():
    if flag==0:
        messagebox.showwarning('Warning',"No Image Selected")
    else:
        file=x
        cv2.imwrite(file,temp_img)
        open_img_direct(file)

In [2]:
from tkinter import *
from tkinter import messagebox
import PIL
import cv2
import numpy as np
import copy 
from tkinter import filedialog
from PIL import Image, ImageTk
root=Tk()
flag=0
root.geometry("600x450")
root.title('My Image Editor')
menu=Menu(root)
root.config(menu=menu)

submenu=Menu(menu)
menu.add_cascade(label="File",menu=submenu)

submenu.add_command(label="New file",command=None)
submenu.add_command(label="Open",command=open_img)
submenu.add_command(label="Save",command=None)

submenu.add_separator()
submenu.add_command(label="Exit",command=None)

#**********ToolBar**********

toolbar=Frame(root,bg="cyan2")
Button(toolbar,text="Resize",command=resize).grid(row=0,column=0,columnspan=2,padx=10,pady=10)
Button(toolbar,text="Draw Line",command=addline).grid(row=0,column=3,columnspan=2,padx=10,pady=10)
Button(toolbar,text="Undo",command=undo).grid(row=0,column=6,columnspan=2,padx=10,pady=10)
Button(toolbar,text="Select Color",command=select_your_colour).grid(row=0,column=9,columnspan=2,padx=10,pady=10)
Button(toolbar,text="Blend Images",command=merge_images).grid(row=0,column=12,columnspan=2,padx=10,pady=10)
#Button(toolbar,text="Smooth",command=smoothing).grid(row=0,column=15,columnspan=2,padx=10,pady=10)
Button(toolbar,text="BrightNess And Contrast",command=BrightNess).grid(row=0,column=15,columnspan=2,padx=10,pady=10)

Button(toolbar,text="About Us",command=None).grid(row=0,column=18,columnspan=2,padx=10,pady=10)
toolbar.grid(row=2,column=0,columnspan=20)

btn = Button(toolbar, text ='Open Image', command = open_img).grid( 
                                        row = 2, column=5,columnspan =2 ) 

#*******Status Bar********
status=Label(root,text="Hang on!!!!!!!!!!!!!",bd=1,relief=SUNKEN,anchor=W)#bd-border
#status.grid(row=17,sticky=SW)

#****************creating image*************************

root.resizable(width = True, height = True) 
  
# Create a button and place it into the window using grid layout 

root.mainloop()

In [4]:
import math
print(5781%9)

3


In [19]:
a=9

NameError: name 'dtype' is not defined

In [5]:
a=[1,2,3,4]
be=np.ones((4,4))*4
print(be)

[[4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]]
